///////////////////////////////////////////////////////////
//  SWRL.cs
//  Implementation of the Class SWRL
//  Generated by Enterprise Architect
//  Created on:      08-дек-2022 15:44:12
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class SWRL {

	private String _rlab;
	private String individualPropertyAtom;
	private String ruleml;

	public SWRL(){

	}

	~SWRL(){

	}

	/// 
	/// <param name="Parameter A"></param>
	public void setRldb(String Parameter A){

	}

	/// 
	/// <param name="Parameter"></param>
	public String getIndividualPropertyAtom(Parameter){

		return "";
	}

	public String getRuleml(){

		return "";
	}

}//end SWRL