///////////////////////////////////////////////////////////
//  RuleLM.cs
//  Implementation of the Class RuleLM
//  Generated by Enterprise Architect
//  Created on:      08-дек-2022 14:45:05
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class RuleLM {

	private String _head;
	private String rel;
	private String atom;

	public RuleLM(){

	}

	~RuleLM(){

	}

	/// 
	/// <param name="Parameter A"></param>
	public void setHead(String Parameter A){

	}

	/// 
	/// <param name="Parameter"></param>
	public String getRel(Parameter){

		return "";
	}

	public String getAtom(){

		return "";
	}

}//end RuleLM