///////////////////////////////////////////////////////////
//  Association.cs
//  Implementation of the Class Association
//  Generated by Enterprise Architect
//  Created on:      19-дек-2022 13:04:06
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Association {

	private String from;
	private String to;

	public Association(){

	}

	~Association(){

	}

	/// 
	/// <param name="A"></param>
	public String getFrom(Parameter A){

		return "";
	}

	/// 
	/// <param name="parameter"></param>
	public int setTo(String parameter){

		return 0;
	}

}//end Association