///////////////////////////////////////////////////////////
//  Draw.cs
//  Implementation of the Class Draw
//  Generated by Enterprise Architect
//  Created on:      19-дек-2022 13:04:50
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Draw {

	private String mxCell;
	private String mxGeometry;
	private String association;

	public Draw(){

	}

	~Draw(){

	}

	/// 
	/// <param name="Parameter A"></param>
	public void setCell(String Parameter A){

	}

	/// 
	/// <param name="Parameter"></param>
	public String getGeometry(Parameter){

		return "";
	}

	public String getAssoc(){

		return "";
	}

}//end Draw