///////////////////////////////////////////////////////////
//  EKB.cs
//  Implementation of the Class EKB
//  Generated by Enterprise Architect
//  Created on:      19-дек-2022 13:04:02
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class EKB {

	private String fact;
	private String action;
	private String rule;

	public EKB(){

	}

	~EKB(){

	}

	/// 
	/// <param name="Parameter A"></param>
	public String getFact(Parameter A){

		return "";
	}

	/// 
	/// <param name="Parameter"></param>
	public void setRule(String Parameter){

	}

	/// 
	/// <param name="Parameter A"></param>
	public String getFact(Parameter A){

		return "";
	}

}//end EKB