///////////////////////////////////////////////////////////
//  Form1.cs
//  Implementation of the Class Form1
//  Generated by Enterprise Architect
//  Created on:      19-дек-2022 13:02:57
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Form1 {

	private String filePath;
	private String name;
	private String savePath;
	public Association m_Association;
	public EKB m_EKB;
	public Draw m_Draw;

	public Form1(){

	}

	~Form1(){

	}

	/// 
	/// <param name="Parameter A"></param>
	private void setFiliPath(Parameter A){

	}

	private void convertFile(){

	}

	/// 
	/// <param name="Parameter"></param>
	private void setSavePath(Parameter){

	}

	/// 
	/// <param name="Parameter A"></param>
	private void setFiliPath(Parameter A){

	}

	/// 
	/// <param name="Parameter"></param>
	private void setSavePath(Parameter){

	}

}//end Form1