///////////////////////////////////////////////////////////
//  EA.cs
//  Implementation of the Class EA
//  Generated by Enterprise Architect
//  Created on:      08-дек-2022 0:15:27
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class EA {

	private String Assotiation;
	private String Attribute;
	private String EntityItem;

	public EA(){

	}

	~EA(){

	}

	/// 
	/// <param name="Parameter A"></param>
	public void setAssotiation(String Parameter A){

	}

	/// 
	/// <param name="Parameter"></param>
	public String getAssotiation(Parameter){

		return "";
	}

	public String getAttribute(){

		return "";
	}

}//end EA