///////////////////////////////////////////////////////////
//  Form1.cs
//  Implementation of the Class Form1
//  Generated by Enterprise Architect
//  Created on:      08-дек-2022 0:16:07
//  Original author: worker
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class Form1 {

	private String pathToFile;
	private String pathToSave;
	public EKB role c;
	public EA role b;

	public Form1(){

	}

	~Form1(){

	}

	/// 
	/// <param name="Parameter A"></param>
	private void selectPathToFile(Parameter A){

	}

	private void convertFile(){

	}

	/// 
	/// <param name="Parameter"></param>
	private void selectPathToSave(Parameter){

	}

}//end Form1